# Generated by Django 5.0.14 on 2026-05-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_custom_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fee', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('contract_template', models.TextField(default='CONTRATO DE PRESTACIÓN DE SERVICIOS\n\nEste contrato rige la relación entre {{tenant_name}} y el organizador {{client_name}}.\n\n1. OBJETO: El prestador brindará sus servicios oficiales el día {{event_date}}.\n2. HONORARIOS: Se establece una tarifa de ${{fee}} MXN.\n3. CONDICIONES: Liquidación del 50% anticipado y 50% restante antes del evento.')),
                ('venue_types_json', models.JSONField(blank=True, default=dict, help_text="Custom key-value pairs for venue/event types (e.g. {'festival': 'Festival', 'private': 'Evento Privado'})")),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_inquiries', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Booking Inquiries',
            },
        ),
        migrations.CreateModel(
            name='BookingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signature', models.TextField(blank=True, null=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_fully_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.bookinginquiry')),
            ],
        ),
    ]
