# Generated by Django 5.0.14 on 2026-07-08 17:52

import apps.bookings.models
import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingcontract_pdf_file'),
        ('tenants', '0015_tenant_stripe_publishable_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.bookings.models.custom_contract_pdf_path)),
                ('header_design', models.JSONField(blank=True, default=dict)),
                ('proemio', models.TextField()),
                ('declarations', models.TextField()),
                ('clauses', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.bookings.models.custom_contract_pdf_path)),
                ('is_fully_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_contracts', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomContractSignatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(help_text='Rol personalizado de este firmante (ej. Aval, Arrendatario)', max_length=150)),
                ('signature_base64', models.TextField(blank=True, help_text='Firma digital trazada', null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='bookings.customcontract')),
            ],
        ),
        migrations.CreateModel(
            name='CustomContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.bookings.models.custom_template_logo_path)),
                ('header_design', models.JSONField(blank=True, default=dict, help_text='Configuración visual del membrete')),
                ('proemio', models.TextField(help_text='Texto introductorio del contrato')),
                ('declarations', models.TextField(help_text='Declaraciones de las partes')),
                ('clauses', models.TextField(help_text='Cláusulas y términos del contrato')),
                ('signatories_count', models.PositiveIntegerField(default=2, help_text='Número predeterminado de firmantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='customcontract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='bookings.customcontracttemplate'),
        ),
    ]
