# Generated by Django 5.0.14 on 2026-07-08 18:50

import apps.bookings.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customcontract_customcontractsignatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontract',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.bookings.models.custom_contract_pdf_path),
        ),
        migrations.AlterField(
            model_name='customcontract',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.bookings.models.custom_contract_pdf_path),
        ),
        migrations.AlterField(
            model_name='customcontracttemplate',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.bookings.models.custom_template_logo_path),
        ),
    ]
