# Generated by Django 5.0.14 on 2026-07-10 04:55

import apps.bookings.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_customcontract_logo_alter_customcontract_pdf_file_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontract',
            name='uploaded_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.bookings.models.custom_contract_pdf_path),
        ),
        migrations.AddField(
            model_name='customcontractsignatory',
            name='sig_h',
            field=models.FloatField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='customcontractsignatory',
            name='sig_page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='customcontractsignatory',
            name='sig_w',
            field=models.FloatField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name='customcontractsignatory',
            name='sig_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customcontractsignatory',
            name='sig_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
