# Generated by Django 5.0.14 on 2026-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_customcontract_uploaded_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontract',
            name='clauses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customcontract',
            name='declarations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customcontract',
            name='proemio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
