services:
  backend:
    image: nectar-labs-backend:prod
    build: ./backend
    volumes:
      - ./backend:/app:Z
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - prod_network

  frontend:
    image: nectar-labs-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - /app/.next
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=https://nectarlabs.dev/api
      - API_URL=https://nectarlabs.dev/api
      - NEXT_DISABLE_SOURCEMAPS=1
    networks:
      - prod_network

volumes:
  postgres_data:

networks:
  prod_network:
    external: true
