services:
  backend:
    container_name: nectar_backend
    image: nectar-labs-backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    restart: always
    networks:
      - prod_network

  frontend:
    container_name: nectar_frontend
    image: nectar-labs-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        INTERNAL_API_URL: ${INTERNAL_API_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env.prod
    restart: always
    networks:
      - prod_network
    volumes:
      - ./frontend/.next:/app/.next

volumes:
  static_volume:
  media_volume:

networks:
  prod_network:
    external: true
