name: nectarlabs-prod

services:
  backend:
    container_name: nectar_backend
    image: nectar-labs-backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  frontend:
    container_name: nectar_frontend
    image: nectar-labs-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        INTERNAL_API_URL: ${INTERNAL_API_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env.prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  redis:
    container_name: nectar_redis_prod
    image: redis:alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  realtime:
    container_name: nectar_realtime_prod
    image: nectar-labs-realtime:prod
    build:
      context: ./realtime
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - PORT=4000
      - DJANGO_SECRET_KEY=${SECRET_KEY:-}
    restart: always
    depends_on:
      - redis
    networks:
      - prod_network

volumes:
  static_volume:
  media_volume:

networks:
  prod_network:
    external: true
