services:
  backend:
    container_name: nectar_backend
    image: nectar-labs-backend:dev
    build: ./backend
    volumes:
      - ./backend:/app:Z
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - prod_network

  frontend:
    container_name: nectar_frontend
    image: nectar-labs-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - /app/.next
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://nectarlabs.localhost/api
      - API_URL=http://nectar_backend:8000/api
      - NEXT_DISABLE_SOURCEMAPS=0
    networks:
      - prod_network

volumes:
  postgres_data:

networks:
  prod_network:
    driver: bridge
