name: nectarlabs-staging

services:
  backend-staging:
    image: nectar-labs-backend:staging
    container_name: nectar_backend_staging
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:Z
    env_file:
      - .env.staging
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=True
      - REALTIME_INTERNAL_URL=http://realtime:4001
      - REALTIME_INTERNAL_SECRET=nectar-internal-secret

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  frontend-staging:
    image: nectar-labs-frontend:staging
    container_name: nectar_frontend_staging
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://staging.nectarlabs.dev/api
    command: npm run dev -- --webpack
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    env_file:
      - .env.staging
    environment:
      - NEXT_PUBLIC_API_URL=https://staging.nectarlabs.dev/api
      - API_URL=http://backend-staging:8000/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  redis:
    container_name: nectar_redis_staging
    image: redis:alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod_network

  realtime:
    container_name: nectar_realtime_staging
    image: nectar-labs-realtime:staging
    build:
      context: ./realtime
      dockerfile: Dockerfile
    volumes:
      - ./realtime:/app:Z
      - /app/node_modules
    env_file:
      - .env.staging
    environment:
      - PORT=4000
      - INTERNAL_PORT=4001
      - INTERNAL_SECRET=nectar-internal-secret
      - DJANGO_SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    networks:
      - prod_network


networks:
  prod_network:
    external: true
