services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=nectarlabs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    image: nectar-labs-backend:dev
    container_name: nectar_backend
    build: ./backend
    volumes:
      - ./backend:/app:Z
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8000"
    networks:
      - default
      - prod_network

  frontend:
    image: nectar-labs-frontend:dev
    container_name: nectar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://nectarlabs.localhost/api
    ports:
      - "3002:3000"
    networks:
      - default
      - prod_network

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "8081:80"
#    volumes:
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
#    depends_on:
#      - backend
#      - frontend

volumes:
  postgres_data:

networks:
  default:
  prod_network:
    external: true
    name: prod_network
