# Generated by Django 5.0.14 on 2026-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_case_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
