# Generated by Django 5.0.14 on 2026-05-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of completion (0-100)'),
        ),
    ]
