# Generated by Django 5.0.14 on 2026-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_is_active_project_progress_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Github Copilot, OpenAI API, Herramientas de Diseño', max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo mensual o anual en USD', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Mensual'), ('Yearly', 'Anual')], default='Monthly', max_length=20)),
                ('next_payment_date', models.DateField(help_text='Próxima fecha de cobro')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('HETZNER', 'Hetzner'), ('AWS', 'AWS'), ('SUPABASE', 'Supabase'), ('CLOUDFLARE', 'Cloudflare'), ('ZOHO', 'Zoho Mail'), ('DOMAIN', 'Registro de Dominio'), ('OTHER', 'Otro')], default='OTHER', max_length=50)),
                ('name', models.CharField(help_text='Ej: VPS 2GB, Base de datos Supabase, Google Workspace', max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo mensual o anual en USD', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Mensual'), ('Yearly', 'Anual')], default='Monthly', max_length=20)),
                ('next_payment_date', models.DateField(help_text='Próxima fecha límite de pago')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
