# Generated by Django 5.0.14 on 2026-05-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_current_activity_description_and_more'),
        ('shop', '0010_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan directly associated with this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.plan'),
        ),
    ]
