# Generated by Django 5.0.14 on 2026-05-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_project_plan'),
        ('shop', '0010_alter_contract_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(blank=True, help_text='Diseñador asignado', limit_choices_to={'role': 'DESIGNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='designer_plan',
            field=models.ForeignKey(blank=True, help_text='Plan de diseño asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_projects', to='shop.plan'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan directly associated with this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='shop.plan'),
        ),
    ]
