# Generated by Django 5.0.14 on 2026-05-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_projectquote_pdf_file'),
        ('shop', '0027_stripeevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios de la cita', null=True)),
                ('is_confirmed_by_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(blank=True, help_text='Servicio/Addon de interés para la consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='shop.addon')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dashboard.lead')),
                ('salesperson', models.ForeignKey(help_text='Vendedor/Agente asignado para la cita', on_delete=django.db.models.deletion.CASCADE, related_name='lead_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('salesperson', 'date', 'time')},
            },
        ),
    ]
