# Generated by Django 5.0.14 on 2026-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_leadappointment'),
        ('shop', '0027_stripeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadappointment',
            name='addons',
            field=models.ManyToManyField(blank=True, help_text='Servicios/Addons de interés para la consulta', related_name='consultations_m2m', to='shop.addon'),
        ),
    ]
