# Generated by Django 5.0.14 on 2026-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_leadappointment_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadappointment',
            name='consulting_type',
            field=models.CharField(choices=[('partner', 'Contrato de Socio Tecnológico'), ('general', 'Consultoría General')], default='general', help_text='Tipo de consultoría seleccionada', max_length=50),
        ),
        migrations.AddField(
            model_name='leadappointment',
            name='interview_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas a las preguntas de la entrevista base'),
        ),
    ]
