# Generated by Django 5.0.14 on 2026-05-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('BUSINESS', 'Business Owner'), ('ANALYST', 'Data Analyst'), ('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('DEVELOPER', 'Developer')], default='CUSTOMER', max_length=20),
        ),
    ]
