# Generated by Django 5.0.14 on 2026-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_email_verified_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Código de referido/vendedor utilizado en el registro.', max_length=50, null=True),
        ),
    ]
