# Generated by Django 5.0.14 on 2026-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles secundarios asignados al usuario.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('BUSINESS', 'Business Owner'), ('ANALYST', 'Data Analyst'), ('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('DEVELOPER', 'Developer'), ('SALES', 'Salesperson'), ('STAFF', 'Staff'), ('DRIVER', 'Driver / Repartidor')], default='CUSTOMER', max_length=20),
        ),
    ]
