# Generated by Django 5.0.14 on 2026-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_additional_roles_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Preferencias de interfaz y estado de tutoriales completados.'),
        ),
    ]
