# Generated by Django 5.0.14 on 2026-06-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_sat_normalized_fields'),
        ('tenants', '0013_tenant_newsletter_last_reset_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio de Nota')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (MXN)')),
                ('payment_method', models.CharField(default='01', max_length=50, verbose_name='Forma de Pago SAT')),
                ('status', models.CharField(choices=[('PAID', 'Pagada'), ('INVOICED', 'Facturada'), ('CANCELLED', 'Cancelada')], default='PAID', max_length=20, verbose_name='Estado de la Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_notes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('product_key', models.CharField(default='01010101', max_length=20, verbose_name='Clave SAT de Producto')),
                ('unit_key', models.CharField(default='E48', max_length=20, verbose_name='Clave SAT de Unidad')),
                ('sales_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.salesnote')),
            ],
        ),
    ]
