# Generated by Django 5.0.14 on 2026-09-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_salesnote_salesnoteitem'),
        ('tenants', '0021_rename_skydropx_api_key_tenant_envia_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso / Nota de Crédito'), ('P', 'Pago / Complemento'), ('T', 'Traslado'), ('G', 'Global')], default='I', max_length=5, verbose_name='Tipo de CFDI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_livemode',
            field=models.BooleanField(default=False, help_text='True si fue timbrado con la llave live ante el SAT; False si es sandbox/pruebas.', verbose_name='CFDI emitido en Modo Producción SAT'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stamp_deducted',
            field=models.BooleanField(default=False, help_text='Garantiza idempotencia en la deducción de la cartera de timbres del tenant.', verbose_name='Timbre Deducido de Cartera'),
        ),
        migrations.CreateModel(
            name='StampTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CONSUMPTION', 'Consumo por Timbrado'), ('REFUND', 'Reembolso por Timbrado Fallido'), ('PURCHASE', 'Compra de Paquete'), ('MONTHLY_RESET', 'Reinicio Mensual de Cortesía'), ('MANUAL_ADJUSTMENT', 'Ajuste Manual')], default='CONSUMPTION', max_length=30)),
                ('amount', models.IntegerField(help_text='Cantidad de timbres agregados (+) o consumidos (-)')),
                ('balance_before', models.PositiveIntegerField(default=0)),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_transactions', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_transactions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
