# Generated by Django 5.0.14 on 2026-05-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
