# Generated by Django 5.0.14 on 2026-05-10 21:39

import apps.shop.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=apps.shop.storage.R2ContractStorage(), upload_to='contracts/'),
        ),
    ]
