# Generated by Django 5.0.14 on 2026-05-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='developer_signature',
            field=models.TextField(blank=True, help_text='Nectar Labs signature', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='developer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_fully_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature_base64',
            field=models.TextField(help_text='Client signature'),
        ),
    ]
