# Generated by Django 5.0.14 on 2026-05-19 06:43

import apps.shop.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_contract_brand_design_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/contracts/', location=pathlib.PurePosixPath('/app/media/contracts')), upload_to=apps.shop.models.contract_pdf_path),
        ),
    ]
