# Generated by Django 5.0.14 on 2026-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_commitment_method',
            field=models.CharField(choices=[('STRIPE', 'Tarjeta (Stripe)'), ('SPEI', 'Transferencia Electrónica (SPEI)'), ('DEPOSIT', 'Depósito Directo (BBVA)')], default='SPEI', max_length=20),
        ),
    ]
