# Generated by Django 5.0.14 on 2026-05-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contract_payment_commitment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Mes de pago (1 de 6, 2 de 6, etc.)')),
                ('due_date', models.DateField(help_text='Fecha límite de pago')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto mensual total (Plan + Adiciones)', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Método usado para este pago', max_length=50, null=True)),
                ('receipt_file', models.FileField(blank=True, help_text='Comprobante de SPEI/Depósito subido por cliente', null=True, upload_to='receipts/%Y/%m/')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=150, null=True)),
                ('cfdi_uuid', models.CharField(blank=True, help_text='Folio Fiscal / UUID CFDI del SAT', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='shop.contract')),
            ],
        ),
    ]
