# Generated by Django 5.0.14 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_paymentinstallment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único (ej: live-chat)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Add-on')),
                ('category_badge', models.CharField(max_length=100, verbose_name='Categoría (Badge)')),
                ('description', models.TextField(verbose_name='Descripción Corta')),
                ('detailed_description', models.TextField(verbose_name='Descripción Detallada')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual (MXN)')),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anual (MXN)')),
                ('origin_project', models.CharField(max_length=150, verbose_name='Proyecto Origen')),
                ('source_reference', models.CharField(max_length=255, verbose_name='Referencia de Código')),
                ('complexity', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Muy Alta', 'Muy Alta')], default='Media', max_length=50, verbose_name='Complejidad de Integración')),
                ('server_requirements', models.TextField(verbose_name='Requerimientos de Servidor')),
                ('technical_details', models.JSONField(default=list, help_text='Lista JSON de detalles técnicos (funcionalidades clave)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='shop.addon', verbose_name='Add-ons Incluidos'),
        ),
    ]
