# Generated by Django 5.0.14 on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_addon_contract_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.plan'),
        ),
    ]
