# Generated by Django 5.0.14 on 2026-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_contract_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='shop.addon'),
        ),
    ]
