# Generated by hand on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_addon_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='stripe_yearly_price_id',
            field=models.CharField(blank=True, help_text='ID de precio anual de Stripe para suscripciones directas', max_length=100, null=True),
        ),
    ]
