# Generated by Django 5.0.14 on 2026-05-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_addon_stripe_yearly_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_day',
            field=models.CharField(choices=[('WEEKLY_MONDAY', 'Lunes de cada semana (Semanal)'), ('FORTNIGHTLY_1ST_15TH', 'Días 1 y 15 de cada mes (Quincenal)'), ('MONTHLY_1ST', 'Día 1ero de cada mes (Mensual)')], default='MONTHLY_1ST', max_length=30),
        ),
    ]
