# Generated by Django 5.0.14 on 2026-05-25 04:29

import apps.shop.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_contract_payment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='4a2cf3da8511b920bc5243a7f45be7df', addressing_style='path', bucket_name='nectarlabs', default_acl='private', endpoint_url='https://00e263633ee27c2e8558008e645c21f2.r2.cloudflarestorage.com', file_overwrite=False, region_name='auto', secret_key='e3a178d75e3724532f672f4752e84ce35b18433ee634d200949fdb8bc0f510ce', signature_version='s3v4'), upload_to=apps.shop.models.contract_pdf_path),
        ),
    ]
