# Generated by Django 5.0.14 on 2026-05-27 13:06

import apps.shop.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='installment_type',
            field=models.CharField(choices=[('DEVELOPMENT', 'Desarrollo/Plan'), ('DESIGN', 'Diseño de Marca')], default='DEVELOPMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/contracts/', location=pathlib.PurePosixPath('/app/media/contracts')), upload_to=apps.shop.models.contract_pdf_path),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto del abono', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='installment_number',
            field=models.IntegerField(help_text='Número de abono (1 de 6, 2 de 24, etc.)'),
        ),
    ]
