# Generated by hand on 2026-05-27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_paymentinstallment_installment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                help_text="Porcentaje de descuento de temporada (0 a 100)",
                max_digits=5
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='discount_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                help_text="Porcentaje de descuento especial (0 a 100)",
                max_digits=5
            ),
        ),
    ]
