# Generated by hand on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_plan_discount_percentage_contract_discount_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la promoción (ej: AMIGO10)', max_length=50, unique=True)),
                ('code_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('SELLER', 'Vendedor')], default='CLIENT', help_text='Tipo de referido', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.00, help_text='Porcentaje de descuento que otorga (0 a 100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el código está activo')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Límite de usos permitidos (nulo para ilimitado)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Veces que ha sido utilizado')),
                ('valid_until', models.DateField(blank=True, help_text='Fecha límite de validez', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, help_text='Usuario que refirió este código (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='shop.promocode'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.00, help_text='Monto base sin descuentos', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.00, help_text='Porcentaje de descuento aplicado a este pago', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='shop.promocode'),
        ),
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado al Vendedor')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='shop.paymentinstallment')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
