# Generated by Django 5.0.14 on 2026-05-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_contract_project_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto final a pagar (después de descuentos)', max_digits=10),
        ),
    ]
