# Generated by Django 5.0.14 on 2026-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_addonsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsubscription',
            name='is_activated',
            field=models.BooleanField(default=True, help_text='Indica si el add-on ha sido activado por el administrador para este inquilino.'),
        ),
    ]
