# Generated by Django 5.0.14 on 2026-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_addonsubscription_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='wants_invoice',
            field=models.BooleanField(default=False, help_text='Si el cliente requiere factura para esta mensualidad'),
        ),
    ]
