# Generated by Django 5.0.14 on 2026-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_paymentinstallment_wants_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indica si se ha enviado el recordatorio de pago.'),
        ),
    ]
