# Generated by Django 5.0.14 on 2026-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_paymentinstallment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery'), ('STRIPE', 'Stripe')], default='CASH', help_text='Método de pago seleccionado por el cliente', max_length=20),
        ),
    ]
