# Generated by Django 5.0.14 on 2026-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp explícito de aceptación de términos y alcance', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_version_hash',
            field=models.CharField(blank=True, help_text='Hash SHA-256 del texto del contrato firmado', max_length=64, null=True),
        ),
    ]
