# Generated by Django 5.0.14 on 2026-09-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_contract_accepted_terms_at_and_more'),
        ('tenants', '0021_rename_skydropx_api_key_tenant_envia_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviaWebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROCESSED', 'Procesado'), ('IGNORED', 'Ignorado'), ('ERROR', 'Error')], default='PROCESSED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Webhook Envia.com',
                'verbose_name_plural': 'Logs de Webhook Envia.com',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='skydropx_rate_id',
            new_name='shipping_rate_id',
        ),
        migrations.AddField(
            model_name='order',
            name='envia_shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier_name',
            field=models.CharField(blank=True, help_text='Identificador Envia (fedex, dhl, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_real',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo neto descontado por Envia.com', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_tenant',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto descontado de la billetera del tenant (Costo Real + $10 MXN)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_name',
            field=models.CharField(blank=True, help_text='Servicio (express, ground, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo base courier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, help_text='Ej: FedEx, DHL, Estafeta', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShippingWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción (positivo para recarga/reembolso, negativo para cargos)', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Saldo disponible en billetera inmediatamente después de la transacción', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('RECHARGE', 'Recarga de Saldo'), ('LABEL_DEBIT', 'Emisión de Guía'), ('SURCHARGE_DEBIT', 'Sobrepeso / Cargo Extra'), ('REFUND', 'Reembolso / Cancelación de Guía'), ('ADJUSTMENT', 'Ajuste Administrativo')], default='LABEL_DEBIT', max_length=30)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='ID de Stripe, shipment_id de Envia o tracking_number', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detalle explícito del concepto (desglose costo courier + comisión Nectar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shop.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_wallet_transactions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transacción de Billetera de Envíos',
                'verbose_name_plural': 'Transacciones de Billetera de Envíos',
                'ordering': ['-created_at'],
            },
        ),
    ]
