# Generated by Django 5.0.14 on 2026-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_enviawebhookeventlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_error',
            field=models.TextField(blank=True, help_text='Detalle del fallo si la emisión de guía en Envia.com no tuvo éxito', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
