# Generated by Django 5.0.14 on 2026-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_enviawebhookeventlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkydropxWebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('shipment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('IGNORED', 'Ignorado'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Webhook Skydropx',
                'verbose_name_plural': 'Logs de Webhook Skydropx',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='request_shipping_invoice',
            field=models.BooleanField(default=False, help_text='Solicitud del comprador para facturar el costo de envío (CFDI 4.0)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider_type',
            field=models.CharField(choices=[('ENVIA', 'Envia.com'), ('SKYDROPX', 'Skydropx Pro')], default='ENVIA', help_text='Proveedor logístico que emitió la guía', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='skydropx_shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier_name',
            field=models.CharField(blank=True, help_text='Identificador courier (fedex, dhl, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_error',
            field=models.TextField(blank=True, help_text='Detalle del fallo si la emisión de guía no tuvo éxito', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, help_text='Ej: FedEx, DHL, Estafeta, Paquetexpress', max_length=50, null=True),
        ),
    ]
