# Generated by Django on 2026-09-17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_skydropxwebhookeventlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_package_type',
            field=models.CharField(
                blank=True,
                default='box',
                help_text='Tipo de empaque usado para esta orden (box, envelope, pallet)',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_package_weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('1.00'),
                help_text='Peso declarado del paquete al emitir la guía (kg)',
                max_digits=6,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_package_dimensions',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Dimensiones {length, width, height} en cm usadas para la cotización y guía'
            ),
        ),
    ]
