# Generated by Django on 2026-09-17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_order_shipping_package_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingwallettransaction',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Clave de idempotencia única para prevenir cargos o emisiones duplicadas',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='shippingwallettransaction',
            name='courier_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Costo base cobrado por el transportista / paquetería',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='shippingwallettransaction',
            name='platform_fee',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Comisión por gestión de guía cobrada por Nectar Labs ($10.00 MXN)',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='shippingwallettransaction',
            name='adjustment_fee',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Cargo o ajuste por sobrepeso o discrepancia de medidas',
                max_digits=10,
            ),
        ),
    ]
