# Generated by Django 5.0.14 on 2026-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BICYCLE', 'Bicicleta'), ('MOTORCYCLE', 'Motocicleta'), ('CAR', 'Automóvil')], default='MOTORCYCLE', max_length=20),
        ),
    ]
