# Generated by Django 5.0.14 on 2026-07-03 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_vehicle_vehicle_type'),
        ('tenants', '0013_tenant_newsletter_last_reset_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfig',
            name='driver_search_radius_km',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='enable_realtime',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BICYCLE', 'Bicicleta'), ('MOTORCYCLE', 'Motocicleta'), ('CAR', 'Automóvil'), ('VAN', 'Camioneta')], default='MOTORCYCLE', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicicleta'), ('MOTORCYCLE', 'Motocicleta'), ('CAR', 'Automóvil'), ('VAN', 'Camioneta')], default='MOTORCYCLE', max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('max_concurrent_orders', models.PositiveSmallIntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Repartidor',
                'verbose_name_plural': 'Perfiles de Repartidores',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('shipment_type', models.CharField(choices=[('LOCAL', 'Entrega local (repartidor)'), ('NATIONAL', 'Envío nacional (paquetería)')], default='LOCAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de asignación'), ('ASSIGNED', 'Repartidor asignado'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En camino'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido / No entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('skydropx_shipment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('courier', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='tenants.tenant')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='delivery.driverprofile')),
            ],
            options={
                'verbose_name': 'Orden de Entrega',
                'verbose_name_plural': 'Órdenes de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_photo_url', models.URLField(blank=True, null=True)),
                ('available_box_sizes', models.CharField(default='S,M,L', max_length=200)),
                ('custom_box_length_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_box_width_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_box_height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_box_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipment_category', models.CharField(choices=[('FOOD_LOCAL', 'Comida / entrega local'), ('DOCUMENT', 'Documentos'), ('FRAGILE', 'Artículos frágiles'), ('ELECTRONICS', 'Electrónicos'), ('CLOTHING', 'Ropa / accesorios'), ('GENERAL', 'Mercancía general')], default='GENERAL', max_length=30)),
                ('offers_local_delivery', models.BooleanField(default=True)),
                ('offers_national_shipping', models.BooleanField(default=False)),
                ('skydropx_api_key', models.CharField(blank=True, max_length=300, null=True)),
                ('shipping_markup_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('origin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('origin_street', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_state', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_country', models.CharField(default='MX', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
            },
        ),
    ]
