# Generated by Django 5.0.14 on 2026-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryconfig_driver_search_radius_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_photo',
            field=models.ImageField(blank=True, help_text='Fotografía de la licencia de conducir.', null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, help_text='Fotografía del vehículo.', null=True, upload_to='driver_vehicles/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si el conductor ha sido verificado y aprobado por el administrador.'),
        ),
    ]
