# Generated by Django 5.0.14 on 2026-07-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_driverprofile_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='rejected_by_drivers',
            field=models.ManyToManyField(blank=True, help_text='Repartidores que han rechazado esta orden en el ciclo de búsqueda.', related_name='rejected_orders', to='delivery.driverprofile'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de asignación'), ('WAITING_ACCEPTANCE', 'Esperando aceptación del repartidor'), ('ASSIGNED', 'Repartidor asignado'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En camino'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido / No entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
