# Generated by Django 5.0.14 on 2026-09-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryorder_rejected_by_drivers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='skydropx_shipment_id',
            new_name='courier_shipment_id',
        ),
        migrations.RenameField(
            model_name='storeconfig',
            old_name='skydropx_api_key',
            new_name='envia_api_key',
        ),
    ]
