# Generated by Django 5.0.14 on 2026-07-10 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_slug', models.SlugField(help_text="Identificador del curso, ej: 'ingeniero-python'", max_length=100)),
                ('module_id', models.CharField(help_text="ID del módulo, ej: '01', '02'", max_length=10)),
                ('code', models.TextField(help_text='Código escrito por el alumno')),
                ('language', models.CharField(default='python', help_text='Lenguaje del ejercicio: python, typescript, elixir, yaml, hcl', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Puntaje de 0 a 100 otorgado por el evaluador')),
                ('feedback', models.TextField(blank=True, help_text='Retroalimentación detallada del evaluador')),
                ('stdout', models.TextField(blank=True, help_text='Salida estándar del sandbox de ejecución')),
                ('stderr', models.TextField(blank=True, help_text='Salida de error del sandbox de ejecución')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Tiempo de ejecución en milisegundos')),
                ('is_completed', models.BooleanField(default=False, help_text='True si el score >= 60 (umbral de aprobación)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Ejercicio',
                'verbose_name_plural': 'Entregas de Ejercicios',
                'ordering': ['course_slug', 'module_id'],
                'unique_together': {('user', 'course_slug', 'module_id')},
            },
        ),
    ]
