# Generated by Django 5.0.14 on 2026-07-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tenants', '0017_tenant_custom_backend_url_tenant_custom_frontend_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisesubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant en el cual se almacena el progreso de este ejercicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesubmission',
            unique_together={('user', 'course_slug', 'module_id', 'tenant')},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('slug', models.SlugField(help_text="Identificador único del curso, ej: 'ingeniero-python'", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant propietario del curso (nulo si es un curso global de Nectar Labs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(help_text="ID del módulo, ej: '01', '02'", max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('badge', models.CharField(help_text="Badge del módulo, ej: 'MÓDULO 01'", max_length=50)),
                ('folder', models.CharField(help_text='Nombre de la carpeta del módulo', max_length=150)),
                ('teoria', models.TextField(blank=True, help_text='Contenido teórico en Markdown')),
                ('ejemplos', models.TextField(blank=True, help_text='Código de ejemplo')),
                ('ejercicios', models.TextField(blank=True, help_text='Código base del ejercicio')),
                ('language', models.CharField(default='python', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Módulo de Curso',
                'verbose_name_plural': 'Módulos de Cursos',
                'ordering': ['course', 'module_id'],
                'unique_together': {('course', 'module_id')},
            },
        ),
    ]
