# Generated by Django 5.0.14 on 2026-05-22 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.SlugField(unique=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('allowed_origins', models.TextField(blank=True, help_text='Allowed origins for embedding the widget, separated by commas or newlines.')),
                ('custom_domain', models.CharField(blank=True, db_index=True, help_text='Custom custom domain mapping (e.g. support.myclient.com).', max_length=255, null=True, unique=True)),
                ('theme_color', models.CharField(default='#C68A1E', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('welcome_message', models.TextField(default='¡Hola! ¿En qué podemos ayudarte hoy?')),
                ('require_customer_info', models.BooleanField(default=True, help_text='Whether to require customer Name and Email before starting a support session.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
