# Generated by Django 5.0.14 on 2026-05-25 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_extra_credits',
            field=models.PositiveIntegerField(default=0, help_text='Créditos extra de correo contratados (múltiplos de 10,000)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_plan',
            field=models.CharField(choices=[('TRIAL', 'Periodo de prueba'), ('PREMIUM', 'Plan Premium ($79)')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_sent_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
