# Generated by Django 5.0.14 on 2026-05-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_custom_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pollen_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pollen_color',
            field=models.CharField(default='#C68A1E', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pollen_icon',
            field=models.CharField(default='⚫', max_length=50),
        ),
    ]
