# Generated by Django 5.0.14 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_pollen_active_tenant_pollen_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme_color_light',
            field=models.CharField(default='#C68A1E', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accent_color_light',
            field=models.CharField(default='#10B981', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bg_color_light',
            field=models.CharField(default='#FAFAFA', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='card_bg_color_light',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='text_color_light',
            field=models.CharField(default='#111827', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='border_color_light',
            field=models.CharField(default='#E5E7EB', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pollen_count',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pollen_blur',
            field=models.FloatField(default=0.2),
        ),
    ]
