# Generated by Django 5.0.14 on 2026-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_skydropx_and_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='invoicing_mode',
            field=models.CharField(choices=[('AUTOMATIC', 'Facturación Automática (al pagar)'), ('MANUAL_CLIENT', 'Manual por el Cliente'), ('MANUAL_ADMIN', 'Manual por el Administrador')], default='AUTOMATIC', help_text='Preferencia de facturación para los abonos de este inquilino.', max_length=20),
        ),
    ]
