# Generated by Django 5.0.14 on 2026-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_newsletter_last_reset_alter_tenant_stamps_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='invoicing_mode',
            field=models.CharField(choices=[('AUTOMATIC', 'Facturación Automática (al pagar)'), ('MANUAL_CLIENT', 'Manual por el Cliente'), ('MANUAL_ADMIN', 'Manual por el Administrador')], default='MANUAL_CLIENT', help_text='Preferencia de facturación para los abonos de este inquilino.', max_length=20),
        ),
    ]
