# Generated by Django 5.0.14 on 2026-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_use_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_context',
            field=models.TextField(blank=True, help_text='Contexto personalizado que se le inyecta al bot de soporte de IA.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la prueba gratuita de 14 días.', null=True),
        ),
    ]
