# Generated by Django 5.0.14 on 2026-06-23 14:40

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_tenant_context_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='newsletter_last_reset_day',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Último día en el que se reinició el contador diario de correos.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_sent_today',
            field=models.PositiveIntegerField(default=0, help_text='Correos masivos enviados el día de hoy.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shipping_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible para pagar guías de envío de Skydropx en Néctar Labs.', max_digits=10),
        ),
    ]
