# Generated by Django 5.0.14 on 2026-07-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_newsletter_last_reset_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='store_category',
            field=models.CharField(blank=True, default='General', help_text='Categoría de la tienda/negocio (ej: Consumibles, Ropa, Tecnología, Comida, etc.)', max_length=100),
        ),
    ]
