# Generated by Django 5.0.14 on 2026-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='Clave pública de Stripe del Tenant', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Clave secreta de Stripe del Tenant', max_length=255, null=True),
        ),
    ]
