# Generated by Django 5.0.14 on 2026-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_custom_css_tenant_custom_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_backend_url',
            field=models.URLField(blank=True, help_text='URL de backend personalizada para redirigir peticiones API', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_frontend_url',
            field=models.URLField(blank=True, help_text='URL de frontend personalizada para enmascarar en iframe', max_length=500, null=True),
        ),
    ]
