# Generated by Django 5.0.14 on 2026-07-29 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenant_custom_backend_url_tenant_custom_frontend_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del Negocio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(unique=True, verbose_name='Subdominio Nectar'),
        ),
    ]
