# Generated by Django 5.0.14 on 2026-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantpage_tenantnavitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='frontend_mode',
            field=models.CharField(choices=[('NATIVE', 'Plantilla Nativa (Nectar Labs Glassmorphism)'), ('CUSTOM_STANDALONE', 'Plantilla Personalizada (BYO Frontend / Proxy)')], default='NATIVE', help_text='Modo de renderizado del frontend para este Tenant (Nativa Glassmorphism vs Personalizada BYO)', max_length=25),
        ),
    ]
