# Generated by Django 5.0.14 on 2026-09-13 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_frontend_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='skydropx_api_key',
            new_name='envia_api_key',
        ),
        migrations.AddField(
            model_name='tenant',
            name='platform_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Comisión fija de Néctar Labs por guía emitida (MXN)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='shipping_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de ganancia sobre el costo del courier hacia el comprador', max_digits=5),
        ),
    ]
