# Generated by Django 5.0.14 on 2026-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_rename_skydropx_api_key_tenant_envia_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_invoice_shipping',
            field=models.BooleanField(default=False, help_text='Timbrar automáticamente el flete con Facturapi al confirmar la orden (opcional)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_shipping_provider',
            field=models.CharField(choices=[('ENVIA', 'Envia.com'), ('SKYDROPX', 'Skydropx Pro'), ('DYNAMIC_BEST', 'Multicotizador Dinámico (Mejor Tarifa)')], default='DYNAMIC_BEST', help_text='Proveedor preferido o multicotizador simultáneo entre proveedores', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='skydropx_client_id',
            field=models.CharField(blank=True, help_text='Client ID de Skydropx Pro (BYO Key)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='skydropx_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret de Skydropx Pro (BYO Key)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='skydropx_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret/Token para webhook de Skydropx', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='envia_api_key',
            field=models.CharField(blank=True, help_text='API Token propio de Envia.com (BYO Key)', max_length=255, null=True),
        ),
    ]
