# Generated by Django on 2026-09-17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_tenant_auto_invoice_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_package_type',
            field=models.CharField(
                choices=[
                    ('BOX', 'Caja Estándar (20x15x10 cm, 1 kg)'),
                    ('ENVELOPE', 'Sobre / Documentos (30x20x2 cm, 0.3 kg)'),
                    ('SMALL_BOX', 'Caja Pequeña (15x15x10 cm, 0.5 kg)'),
                    ('MEDIUM_BOX', 'Caja Mediana (30x25x20 cm, 2.0 kg)'),
                    ('LARGE_BOX', 'Caja Grande (50x40x30 cm, 5.0 kg)'),
                    ('PALLET', 'Tarima / Pallet (120x100x150 cm, 150 kg)'),
                    ('CUSTOM', 'Personalizado')
                ],
                default='BOX',
                help_text='Tipo de empaque predeterminado para cotizaciones y guías (Caja, Sobre, Tarima)',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_package_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1.00'),
                help_text='Peso predeterminado del paquete en kilogramos (kg)',
                max_digits=6
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_package_length',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('20.00'),
                help_text='Largo predeterminado en centímetros (cm)',
                max_digits=6
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_package_width',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('15.00'),
                help_text='Ancho predeterminado en centímetros (cm)',
                max_digits=6
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_package_height',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('10.00'),
                help_text='Alto predeterminado en centímetros (cm)',
                max_digits=6
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_package_content',
            field=models.CharField(
                blank=True,
                default='Mercancía general',
                help_text='Descripción genérica del contenido del envío',
                max_length=255,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_declared_value',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('500.00'),
                help_text='Valor declarado por defecto en MXN',
                max_digits=10
            ),
        ),
    ]
