# Generated by Django on 2026-09-17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_tenant_default_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='shipping_markup_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Porcentaje de ganancia sobre el costo del courier hacia el comprador',
                max_digits=5,
            ),
        ),
    ]
