# Generated by Django on 2026-09-17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0024_alter_tenant_shipping_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='tenant_favicons/',
                verbose_name='Favicon del Portal (.ico, .png, .svg)'
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL externa de Favicon'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wallet_balance',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Saldo universal para timbrado CFDI (Facturapi), paquetería (Envia/Skydropx) y Amazon SES.',
                max_digits=12,
                verbose_name='Billetera Unificada Nectar Labs (MXN)'
            ),
        ),
        migrations.CreateModel(
            name='TenantWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(
                    choices=[
                        ('INVOICING_CFDI', 'Facturación CFDI 4.0 (Facturapi)'),
                        ('SHIPPING_LABEL', 'Guía de Paquetería (Envia / Skydropx)'),
                        ('EMAIL_SES', 'Amazon SES / Email Marketing'),
                        ('RECHARGE', 'Recarga de Saldo Billetera'),
                        ('REFUND', 'Reembolso por Servicio Fallido'),
                        ('ADJUSTMENT', 'Ajuste Administrativo'),
                        ('OTHER', 'Otro Servicio')
                    ],
                    default='OTHER',
                    max_length=30,
                    verbose_name='Tipo de Servicio'
                )),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (+Abono / -Cargo)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Previo (MXN)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Posterior (MXN)')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción / Concepto')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='ID de Referencia Externa')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Operación')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='tenants.tenant', verbose_name='Inquilino')),
            ],
            options={
                'verbose_name': 'Transacción de Billetera Unificada',
                'verbose_name_plural': 'Transacciones de Billetera Unificada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Producción')], default='staging', max_length=20, verbose_name='Ambiente')),
                ('action', models.CharField(choices=[('DEPLOY', 'Desplegar / Build Completo'), ('START', 'Iniciar Contenedores'), ('STOP', 'Detener Contenedores'), ('RESTART', 'Reiniciar Contenedores'), ('STATUS', 'Inspección de Salud')], default='DEPLOY', max_length=20, verbose_name='Acción Solicitada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Ejecución'), ('SUCCESS', 'Completado con Éxito'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Ejecución')),
                ('output_logs', models.TextField(blank=True, default='', verbose_name='Registro de Logs en Vivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='tenants.tenant', verbose_name='Inquilino')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
            ],
            options={
                'verbose_name': 'Despliegue de Inquilino',
                'verbose_name_plural': 'Despliegues de Inquilinos',
                'ordering': ['-created_at'],
            },
        ),
    ]
