# Generated by Django on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_tenant_favicon_wallet_deployments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deployment_repo_path',
            field=models.CharField(
                blank=True,
                help_text='Ruta absoluta al repositorio en el servidor (ej: /var/www/Finanzasparahippies). Si se deja vacío, se autodescubrirá en /var/www.',
                max_length=255,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deployment_backend_container',
            field=models.CharField(
                blank=True,
                help_text='Nombre explícito del contenedor backend en Docker (ej: fph_backend_staging). Si está vacío, se detecta desde compose.',
                max_length=150,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deployment_frontend_container',
            field=models.CharField(
                blank=True,
                help_text='Nombre explícito del contenedor frontend en Docker (ej: fph_frontend_staging). Si está vacío, se detecta desde compose.',
                max_length=150,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_standalone_repo',
            field=models.BooleanField(
                default=False,
                help_text='Indica si este tenant opera con stack Docker dedicado autónomo en lugar de la plantilla nativa compartida.'
            ),
        ),
    ]
