# Generated by Django 5.0.14 on 2026-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_tenant_deployment_orchestration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hosting_type',
            field=models.CharField(choices=[('LOCAL', 'Local / Contenedor Néctar'), ('REMOTE', 'Servidor Remoto Externo')], default='LOCAL', help_text='Infraestructura donde corre el inquilino (Local Docker en Néctar vs Servidor Remoto Externo)', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='remote_health_url',
            field=models.URLField(blank=True, help_text='URL de Healthcheck o monitoreo en el servidor remoto (ej: https://staging.msambar.com/api/health/)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='remote_server_ip',
            field=models.CharField(blank=True, help_text='Dirección IP del servidor remoto (ej: 5.78.195.30)', max_length=100, null=True),
        ),
    ]
