# Generated by Django 5.0.14 on 2026-05-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tenant_supportchat_supportchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchatmessage',
            name='is_ai_message',
            field=models.BooleanField(default=False, help_text='True if this message was generated by the AI assistant'),
        ),
    ]
