# Generated by Django 5.0.14 on 2026-06-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_tenant'),
        ('tenants', '0011_tenant_use_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CampaignTemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_template_images', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='marketing_lists', to='newsletter.subscriber')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_lists', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('template_type', models.CharField(choices=[('minimalist', 'Minimalist Carbon'), ('moss', 'Moss Green'), ('cosmic', 'Cosmic Night'), ('glow', 'Amber Glow'), ('mist', 'Mystic Mist')], default='minimalist', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='campaign_bg/')),
                ('bg_opacity', models.FloatField(default=1.0)),
                ('bg_saturation', models.IntegerField(default=100)),
                ('bg_position', models.CharField(default='center', max_length=50)),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_link', models.URLField(blank=True, default='')),
                ('image_style', models.JSONField(blank=True, default=dict)),
                ('ctas', models.JSONField(blank=True, default=list)),
                ('custom_styles', models.JSONField(blank=True, default=dict)),
                ('font_family', models.CharField(default='serif', max_length=100)),
                ('title_font_family', models.CharField(default='serif', max_length=100)),
                ('footer_font_family', models.CharField(default='serif', max_length=100)),
                ('email_title', models.TextField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant')),
                ('marketing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='newsletter.marketinglist')),
            ],
        ),
    ]
